### ISSUE TITLE
Small font in calculation window on Hidpi monitor

### ISSUE THREAD

**Issue by pozemka** [plastovicka/PreciseCalculator#1]
Please see attached image.
Monitor has 3840×2160 resolution with 175% scaling
![изображение](https://github.com/plastovicka/PreciseCalculator/assets/1259724/59d953e7-7d66-44d6-adbd-8237360f4e5b)

**Comment by plastovicka** [comment]
You can set the font size in the menu File/Font...

**Comment by pozemka** [comment]
Oh! Somehow I've missed this setting :) Thank you!

Just as opinion I think that the font in inputs should match font of the rest window by default. Otherwise it could confuse new users.
